package com.mydomain.OnPass.action;

import java.io.IOException;
import java.util.Date;
import java.util.List;

import javax.mail.MessagingException;
import javax.mail.NoSuchProviderException;
import javax.persistence.EntityManager;

import org.jboss.seam.Component;
import org.jboss.seam.annotations.AutoCreate;
import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Logger;
import org.jboss.seam.annotations.Name;
import org.jboss.seam.annotations.Transactional;
import org.jboss.seam.annotations.async.Asynchronous;
import org.jboss.seam.annotations.async.Expiration;
import org.jboss.seam.annotations.async.FinalExpiration;
import org.jboss.seam.annotations.async.IntervalCron;
import org.jboss.seam.annotations.async.IntervalDuration;
import org.jboss.seam.async.QuartzTriggerHandle;
import org.jboss.seam.log.Log;

import com.mydomain.OnPass.model.Password;
import com.mydomain.OnPass.model.User;

@Name("quartzTimer")
@AutoCreate
public class QuartzTimer {
    SMS sms = new SMS();
    @In("entityManager")
	EntityManager em;
	@Logger
	Log log;

	@Asynchronous
	@Transactional
	public QuartzTriggerHandle createTimer(@Expiration Date when,
			@IntervalDuration Long interval, @FinalExpiration Date stoptime) {
		log.info("Timer event starts...");
		try {

		} catch (Exception e) {
			e.printStackTrace();
		}
		log.info("Timer event ends...");
		return null;
	}

	@Asynchronous
	public QuartzTriggerHandle startJob1(@Expiration Date when,
			@IntervalCron String cron, @FinalExpiration Date endDate) {
        
		log.info("Cron Working Starts...");
        SendNotification();
		return null;
	}
	
	public void SendNotification(){
		List<User> allUsers = em.createQuery("select u from User u").getResultList();
        for(User u:allUsers){
        	String message="";
        	if(u.isExpiryNotify()==true){
        		for(Password p:u.getPass()){
        			if(p.DiffDate()<=3){
        					message = message + "" + p.getPass_name()+ "/"; 
        			}
        		}
        		if(!message.equals("")){
        			message = "Dear, "+u.getFullname()+", you need to change your password(s):" + message  
        			+ ". This message is autogenerated, do not answer it. Thank You";
        			log.info(message);
                    sms.send(u.getNumber(), message);
            }
        	}
        }
	}

}
